import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
public class md5
{
	public static String getMD5(String input){
		    try{
		        MessageDigest md= MessageDigest.getInstance("MD5");
		        
		        byte[] messageDigest=md.digest(input.getBytes());
		        BigInteger num= new BigInteger(1,messageDigest);
		        
		        String hashtext=num.toString(16);
		        while(hashtext.length()<32){
		            hashtext="0"+hashtext;
		        }
		        return hashtext;
		        
		    }
		    catch(NoSuchAlgorithmException e){
		        throw new RuntimeException(e);
		    }
		}
	public static void main(String[] args) {
		String s="GeeksForGeeks";
		System.out.println("Your hashcode generated by MD5: " + getMD5(s));
	}
}
